#pragma once
#include <string>
#include "routes/AuthRoutes.hpp"
#include "routes/ChapterRoutes.hpp"
#include "routes/MemberRoutes.hpp"
#include "routes/MeetingRoutes.hpp"
#include "routes/EventRoutes.hpp"
#include "routes/AttendanceRoutes.hpp"
#include "routes/CalendarRoutes.hpp"
#include "routes/SettingsRoutes.hpp"
#include "routes/RoleRoutes.hpp"
#include "routes/PerkRoutes.hpp"
#include "routes/CheckinRoutes.hpp"
#include "routes/AuditRoutes.hpp"
#include "routes/HelpRoutes.hpp"
#include "routes/ApiKeyRoutes.hpp"
#include "routes/DiscordMatchRoutes.hpp"
#include "routes/DiscordInteractionsRoutes.hpp"
#include "routes/api/MembersApiRoutes.hpp"
#include "routes/api/EventsApiRoutes.hpp"
#include "routes/api/MeetingsApiRoutes.hpp"
#include "routes/api/ChaptersApiRoutes.hpp"
#include "routes/api/ChapterMembersApiRoutes.hpp"
#include "routes/api/AttendanceApiRoutes.hpp"
#include "routes/api/PerkLevelsApiRoutes.hpp"
#include "routes/api/RoleMappingsApiRoutes.hpp"
#include "routes/api/AuditLogApiRoutes.hpp"
#include "routes/api/SettingsApiRoutes.hpp"
#include "repositories/ApiKeyRepository.hpp"
#include "repositories/PendingDiscordMatchRepository.hpp"
#include "repositories/PerkLevelRepository.hpp"
#include "repositories/AttendanceRepository.hpp"
#include "repositories/EventDayRepository.hpp"
#include "repositories/EventDayAttendanceRepository.hpp"
#include "services/MemberService.hpp"
#include "services/MemberSyncService.hpp"
#include "services/MeetingService.hpp"
#include "services/EventService.hpp"
#include "services/ChapterService.hpp"
#include "services/AttendanceService.hpp"
#include "auth/AuthService.hpp"
#include "integrations/DiscordOAuth.hpp"
#include "integrations/DiscordClient.hpp"
#include "integrations/CalendarGenerator.hpp"
#include "integrations/GoogleCalendarClient.hpp"
#include "repositories/SettingsRepository.hpp"
#include "repositories/RoleMappingRepository.hpp"
#include "repositories/ChapterMemberRepository.hpp"
#include "repositories/MeetingRepository.hpp"
#include "repositories/EventRepository.hpp"
#include "services/AuditService.hpp"

struct Services {
    ChapterService&         chapters;
    MemberService&          members;
    MeetingService&         meetings;
    EventService&           events;
    AttendanceService&      attendance;
    AuthService&            auth;
    DiscordOAuth&           oauth;
    DiscordClient&          discord;
    CalendarGenerator&      calendar;
    SettingsRepository&     settings;
    RoleMappingRepository&  role_mappings;
    ChapterMemberRepository& chapter_members;
    MemberSyncService&      member_sync;
    GoogleCalendarClient&   gcal;
    PerkLevelRepository&    perks;
    AttendanceRepository&   attendance_repo;
    MemberRepository&       member_repo;
    MeetingRepository&      meeting_repo;
    EventRepository&        event_repo;
    EventDayRepository&     event_day_repo;
    EventDayAttendanceRepository& event_day_attendance_repo;
    AuditService&           audit;
    ApiKeyRepository&       api_keys;
    PendingDiscordMatchRepository& pending_discord_matches;
    const std::string&      discord_public_key;
};

void register_all_routes(LugApp& app, Services& svc);
