#!/usr/bin/env python3
"""Generates src/static/theme.css - the dark theme.

Dark mode is applied by overriding the light-palette Tailwind utilities the
templates already use (bg-white, bg-gray-50, text-gray-700, bg-red-50, ...)
under html[data-theme="dark"], instead of adding dark: variants to ~1500 class
attributes. The rules are plain (unlayered) CSS, so they beat Tailwind's
@layer utilities regardless of specificity, and they work with the CDN dev
fallback too. Re-run after adding new light-palette utilities:

    python3 scripts/gen_theme_css.py
"""
from pathlib import Path

D = 'html[data-theme="dark"]'
out = []
w = out.append

def esc(cls):
    return cls.replace(':', '\\:').replace('/', '\\/')

w("/* GENERATED by scripts/gen_theme_css.py - edit the generator, not this file. */")
w(f"""{D} {{
  color-scheme: dark;
  --lm-bg: #0e1116;        /* page */
  --lm-surface: #171b22;   /* cards, modal (bg-white) */
  --lm-surface-2: #1e232c; /* bg-gray-50: table heads, subtle fills */
  --lm-surface-3: #262c36; /* bg-gray-100 */
  --lm-surface-4: #303744; /* bg-gray-200 */
  --lm-surface-5: #3b4351; /* bg-gray-300 */
  --lm-border-1: #252a33;
  --lm-border-2: #2e3440;
  --lm-border-3: #3a4250;
  --lm-text-1: #e8ebf0;    /* gray-900 */
  --lm-text-2: #dce0e7;    /* gray-800 */
  --lm-text-3: #c6ccd5;    /* gray-700 */
  --lm-text-4: #a7afba;    /* gray-600 */
  --lm-text-5: #8d96a2;    /* gray-500 */
}}""")

# Page background (body carries bg-gray-100)
w(f"{D} body.bg-gray-100 {{ background-color: var(--lm-bg); }}")

# Surfaces. The sidebar (always dark) uses gray-700..900 and is untouched.
bg = {'bg-white': 'surface', 'bg-gray-50': 'surface-2', 'bg-gray-100': 'surface-3',
      'bg-gray-200': 'surface-4', 'bg-gray-300': 'surface-5'}
for c, v in bg.items():
    w(f"{D} .{c} {{ background-color: var(--lm-{v}); }}")
hover_bg = {'hover:bg-white': 'surface-2', 'hover:bg-gray-50': 'surface-3',
            'hover:bg-gray-100': 'surface-4', 'hover:bg-gray-200': 'surface-5'}
for c, v in hover_bg.items():
    w(f"{D} .{esc(c)}:hover {{ background-color: var(--lm-{v}); }}")

text = {'900': 1, '800': 2, '700': 3, '600': 4, '500': 5}
for shade, n in text.items():
    w(f"{D} .text-gray-{shade} {{ color: var(--lm-text-{n}); }}")
    w(f"{D} .{esc('hover:text-gray-' + shade)}:hover {{ color: var(--lm-text-1); }}")
w(f"{D} .text-black {{ color: var(--lm-text-1); }}")

for shade, n in {'100': 1, '200': 2, '300': 3}.items():
    w(f"{D} .border-gray-{shade} {{ border-color: var(--lm-border-{n}); }}")
    w(f"{D} .divide-gray-{shade} > :not(:last-child) {{ border-color: var(--lm-border-{n}); }}")

# Coloured tints: light washes become low-alpha tints of the hue; dark text
# shades become light ones.
hues = ['red', 'orange', 'amber', 'yellow', 'lime', 'green', 'emerald', 'teal', 'cyan',
        'sky', 'blue', 'indigo', 'violet', 'purple', 'fuchsia', 'pink', 'rose']
for h in hues:
    for shade, pct in {'50': 12, '100': 18, '200': 26}.items():
        mix = f"color-mix(in oklab, var(--color-{h}-500) {pct}%, transparent)"
        w(f"{D} .bg-{h}-{shade} {{ background-color: {mix}; }}")
        hmix = f"color-mix(in oklab, var(--color-{h}-500) {pct + 8}%, transparent)"
        w(f"{D} .{esc('hover:bg-' + h + '-' + shade)}:hover {{ background-color: {hmix}; }}")
    for shade, to in {'600': '400', '700': '300', '800': '200', '900': '200'}.items():
        w(f"{D} .text-{h}-{shade} {{ color: var(--color-{h}-{to}); }}")
        w(f"{D} .{esc('hover:text-' + h + '-' + shade)}:hover {{ color: var(--color-{h}-200); }}")
    for shade, pct in {'100': 25, '200': 35, '300': 45}.items():
        w(f"{D} .border-{h}-{shade} {{ border-color: color-mix(in oklab, var(--color-{h}-500) {pct}%, transparent); }}")

# Exceptions: things that must keep their light-mode look.
w(f"""/* Dark text stays dark on bright brand buttons/badges. */
{D} :is(.bg-yellow-300, .bg-yellow-400, .bg-yellow-500, .bg-amber-300, .bg-amber-400, .nav-active):is(.text-gray-900, .text-gray-800, .text-gray-700, .text-black) {{ color: #111827; }}
/* QR codes need a white quiet zone to scan; the sidebar logo tile stays white. */
{D} #checkin-qr, {D} #checkin-qr.bg-white, {D} .qr-keep-light, {D} #sidebar .bg-white {{ background-color: #fff; }}
{D} img[src$=".svg"].invert-on-dark {{ filter: invert(1) hue-rotate(180deg); }}""")

# Form controls without explicit bg classes, placeholders, focus rings stay yellow.
w(f"""{D} input:not([type=checkbox]):not([type=radio]):not([type=range]):not([type=color]), {D} select, {D} textarea {{
  background-color: var(--lm-surface-2); color: var(--lm-text-1); border-color: var(--lm-border-3);
}}
{D} ::placeholder {{ color: var(--lm-text-5); opacity: 1; }}
{D} .shadow, {D} .shadow-sm, {D} .shadow-md, {D} .shadow-lg, {D} .shadow-2xl {{ --tw-shadow-color: rgb(0 0 0 / 0.5); }}""")

# Third-party widgets
w(f"""/* DataTables */
{D} table.dataTable, {D} .dataTables_wrapper, {D} .dt-container {{ color: var(--lm-text-2); }}
{D} table.dataTable tbody tr, {D} table.dataTable > tbody > tr {{ background-color: transparent; }}
{D} table.dataTable thead th, {D} table.dataTable thead td {{ border-bottom-color: var(--lm-border-3); }}
{D} table.dataTable tbody td, {D} table.dataTable > tbody > tr > td {{ border-top-color: var(--lm-border-2); }}
{D} table.dataTable.stripe > tbody > tr:nth-child(odd) > *, {D} table.dataTable.display > tbody > tr:nth-child(odd) > * {{ box-shadow: inset 0 0 0 9999px rgb(255 255 255 / 0.02); }}
{D} table.dataTable.hover > tbody > tr:hover > *, {D} table.dataTable.display > tbody > tr:hover > * {{ box-shadow: inset 0 0 0 9999px rgb(255 255 255 / 0.05); }}
{D} .dt-paging .dt-paging-button, {D} .dataTables_paginate .paginate_button {{ color: var(--lm-text-3) !important; }}
{D} .dt-paging .dt-paging-button.current, {D} .dataTables_paginate .paginate_button.current {{ background: var(--lm-surface-4) !important; color: var(--lm-text-1) !important; border-color: var(--lm-border-3) !important; }}
/* Tom Select */
/* tom-select's own selectors are very specific (.ts-wrapper:not(.form-control)... .ts-control) */
{D} .ts-control, {D} .ts-wrapper .ts-control, {D} .ts-dropdown, {D} .ts-dropdown .option {{ background: var(--lm-surface-2) !important; background-image: none !important; color: var(--lm-text-1) !important; border-color: var(--lm-border-3) !important; }}
{D} .ts-control input, {D} .ts-control .item {{ color: var(--lm-text-1) !important; }}
{D} .ts-dropdown .active, {D} .ts-dropdown .option:hover {{ background: var(--lm-surface-4) !important; color: var(--lm-text-1) !important; }}
{D} .ts-wrapper.multi .ts-control > div {{ background: var(--lm-surface-4); color: var(--lm-text-1); border-color: var(--lm-border-3); }}
/* EasyMDE / CodeMirror */
{D} .EasyMDEContainer .CodeMirror, {D} .editor-toolbar {{ background: var(--lm-surface-2); color: var(--lm-text-1); border-color: var(--lm-border-3); }}
{D} .editor-toolbar button {{ color: var(--lm-text-3) !important; }}
{D} .editor-toolbar button:hover, {D} .editor-toolbar button.active {{ background: var(--lm-surface-4); border-color: var(--lm-border-3); }}
{D} .CodeMirror-cursor {{ border-left-color: var(--lm-text-1); }}
{D} .editor-preview, {D} .editor-preview-side {{ background: var(--lm-surface); color: var(--lm-text-2); }}
/* driver.js tours */
{D} .driver-popover {{ background: var(--lm-surface); color: var(--lm-text-2); }}
{D} .driver-popover-title {{ color: var(--lm-text-1); }}
{D} .driver-popover-arrow {{ border-color: var(--lm-surface); }}
/* Markdown output */
{D} .prose {{ --tw-prose-body: var(--lm-text-3); --tw-prose-headings: var(--lm-text-1); --tw-prose-links: #facc15; --tw-prose-bold: var(--lm-text-1); --tw-prose-code: var(--lm-text-1); color: var(--lm-text-3); }}
{D} .prose :is(h1,h2,h3,h4,strong) {{ color: var(--lm-text-1); }}
{D} .prose a {{ color: #facc15; }}""")

Path(__file__).resolve().parent.parent.joinpath('src/static/theme.css').write_text('\n'.join(out) + '\n')
print('wrote src/static/theme.css')
